import './globals.css'
import { Montserrat } from 'next/font/google';

const montserrat = Montserrat({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-montserrat", // it's for add to tailwind and use it where u want
}) 

export const metadata = {
  description: 'Generated by create next app',
}


export default function RootLayout({ children}) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} mx-28 my-28`}>
        {children}
      </body>
    </html>
  )
}
